[versions]
agp = "9.4.0"
coroutines = "1.11.0"
kotlin = "2.4.20"
lifecycle = "2.11.0"
kaidl = "0.2.0"
room = "3.0.3"
ktor = "3.6.0"
jvmTarget = "21"
cmp = "1.12.0"
koin = "4.2.2"

[libraries]
kotlin-coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutine-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutine-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0"

androidx-activity-compose = "androidx.activity:activity-compose:1.13.0"
androidx-browser = "androidx.browser:browser:1.10.0"

jetbrains-compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "cmp" }
jetbrains-compose-uiTooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "cmp" }
jetbrains-compose-uiToolingPreview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "cmp" }
jetbrains-compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "cmp" }
jetbrains-compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "cmp" }
jetbrains-compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "cmp" }
jetbrains-compose-material3 = "org.jetbrains.compose.material3:material3:1.11.0-alpha07"
jetbrains-androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
jetbrains-androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
jetbrains-androidx-lifecycle-viewmodelNavigation3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecycle" }
jetbrains-androidx-navigation3-ui = "org.jetbrains.androidx.navigation3:navigation3-ui:1.1.1"

androidx-core = "androidx.core:core:1.19.0"
androidx-room-compiler = { module = "androidx.room3:room3-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room3:room3-runtime", version.ref = "room" }

kaidl-compiler = { module = "io.github.goooler.kaidl:kaidl-compiler", version.ref = "kaidl" }
kaidl-runtime = { module = "io.github.goooler.kaidl:kaidl-runtime", version.ref = "kaidl" }
rikkax-multiprocess = "dev.rikka.rikkax.preference:multiprocess:1.0.0"
quickie-bundled = "io.github.g00fy2.quickie:quickie-bundled:1.12.0"
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
bytesize = "me.saket.bytesize:bytesize:2.2.1"
semver = "net.swiftzer.semver:semver:2.1.0"

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-viewModel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

composePreference = "me.zhanghai.compose.preference:preference:2.2.0"
reorderable = "sh.calvin.reorderable:reorderable:3.1.0"

junit = "junit:junit:4.13.2"
assertk = "com.willowtreeapps.assertk:assertk:0.28.1"
kermit = "co.touchlab:kermit:2.2.0"
# Dummy to get renovate updates, the version is used in rootProject build.gradle with spotless.
ktfmt = "com.facebook:ktfmt:0.64"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-multiplatform = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jb-compose = { id = "org.jetbrains.compose", version.ref = "cmp" }
ksp = "com.google.devtools.ksp:2.3.12"
golang = "io.github.goooler.golang:0.3.0"
download = "de.undercouch.download:5.7.0"
spotless = "com.diffplug.spotless:8.10.2"
