name: Update Clash-Core and Go Modules

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'core/src/foss/golang/clash'

jobs:
  update-go-dependencies:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Goooler' && (github.actor == 'renovate[bot]' || startsWith(github.head_ref, 'renovate/'))
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}
          submodules: recursive
          token: ${{ steps.app-token.outputs.token }}
      - uses: actions/setup-go@v7
        with:
          go-version: "1.27"
          check-latest: true
      - name: Install update-go-mod-replace
        run: |
          go install github.com/metacubex/update-go-mod-replace@latest
      - name: Update Foss Gomod
        run: |
          cd ${{ github.workspace }}/core/src/foss/golang/
          update-go-mod-replace ${{ github.workspace }}/core/src/foss/golang/clash/go.mod $(pwd)/go.mod
          go mod tidy
      - name: Update Main Gomod
        run: |
          cd ${{ github.workspace }}/core/src/main/golang/
          update-go-mod-replace ${{ github.workspace }}/core/src/foss/golang/clash/go.mod $(pwd)/go.mod
          go mod tidy
      - name: Commit and push changes
        env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          if [ -n "$(git status --porcelain core/src/foss/golang/go.mod core/src/foss/golang/go.sum core/src/main/golang/go.mod core/src/main/golang/go.sum)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add core/src/foss/golang/go.mod core/src/foss/golang/go.sum core/src/main/golang/go.mod core/src/main/golang/go.sum
            git commit -m "Update Go dependencies"
            git push origin "HEAD:$HEAD_REF"
          else
            echo "No Go dependency updates needed."
          fi
